language: generic
sudo: required

services:
- docker

script:
- docker build -t tifig .
- docker run -t --rm -w /tifig/build tifig ./tifig -v ../fixtures/1.heic test.jpg
- docker run -t --rm -w /tifig/build tifig ./tifig -v -t ../fixtures/1.heic thumb.jpg



